In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, multivariate_normal

In [2]:
data = np.loadtxt('./winery-multivariate/wine.data.txt', delimiter=',')
featurenames = ['Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash','Magnesium', 'Total phenols', 
                'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 
                'OD280/OD315 of diluted wines', 'Proline']

np.random.seed(0)
perm = np.random.permutation(178)
train_size = 130
feature_size = 14
trainx = data[perm[0:train_size],1:feature_size]
trainy = data[perm[0:train_size],0]
testx = data[perm[train_size:], 1:feature_size]
testy = data[perm[train_size:],0]

In [3]:
print(trainx.shape, trainy.shape, testx.shape, testy.shape)

(130, 13) (130,) (48, 13) (48,)


In [4]:
def fit_generative_model(x, y):
    num_class = 3
    k = num_class
    d = (x.shape)[1]
    mu = np.zeros((k+1, d))
    sigma = np.zeros((k+1, d, d))
    pi = np.zeros(k+1)
    for label in range(1, k+1):
        indices = (y==label)
        mu[label] = np.mean(x[indices,:], axis=0)
        sigma[label] = np.cov(x[indices,:], rowvar=0, bias=1)
        pi[label] = float(sum(indices))/float(len(y))
    return mu, sigma, pi

In [5]:
mu, sigma, pi = fit_generative_model(trainx, trainy)

In [30]:
print(mu.shape, sigma.shape, pi.shape)

f1 = [2,4,6]
print('mu subset = \n', mu[:,f1])
print('cov subset = \n', sigma[:,f1,f1])
print(sub_sigma.shape)
print(sigma.shape)

(4, 13) (4, 13, 13) (4,)
mu subset = 
 [[  0.           0.           0.        ]
 [  2.42790698 105.8372093    2.99627907]
 [  2.22703704  95.83333333   2.10907407]
 [  2.40090909  99.03030303   0.75727273]]
cov subset = 
 [[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.67746890e-02 1.18461871e+02 1.52409410e-01]
 [1.12302332e-01 3.28509259e+02 5.68697291e-01]
 [2.67597796e-02 1.25423324e+02 7.37531680e-02]]
(4, 3)
(4, 13, 13)


In [24]:
def test_model(mu, sigma, pi, features, tx, ty):
    num_class = 3
    sub_mu = mu[:, features]
    sub_sigma = sigma[:, features, features]
    score = np.zeros((len(ty), num_class+1))
    for i in range(len(ty)):
        for label in range(1, num_class+1):
            score[i,label] = np.log(pi[label]) + \
                multivariate_normal.logpdf(tx[i, features], mean=sub_mu[label,:],
                                          cov=sub_sigma[label,:,:])
    predictions = np.argmax(score[:, 1:num_class+1], axis=1) + 1
    errors = np.sum(predictions == ty)
    print("Test error using features: ")
    for f in features:
        print("'" + featurenames[f] + "'" + " ")
    print("Errors: " + str(errors) + "/" + str(len(ty)))

In [25]:
test_model(mu, sigma, pi, [2,4,6], testx, testy)

IndexError: too many indices for array